/// <reference lib="dom" />
import { contextBridge, ipcRenderer } from "electron";
import type { StridetermAPI } from "./shared/ipc-bridge.js";

// Startup flags injected by main via webPreferences.additionalArguments.
// Reading process.argv here is safe — preload runs in the renderer's Node
// context but with the original argv. Synchronous read so the bridge can
// expose the flag without forcing every consumer through an async getter.
const windowIdArg = process.argv.find((arg) => arg.startsWith("--strideterm-window-id="));
const startupWindowId = windowIdArg ? windowIdArg.slice("--strideterm-window-id=".length) : "";

const startupFlags = {
  disableWebgl: process.argv.includes("--strideterm-disable-webgl"),
  windowId: startupWindowId,
};

contextBridge.exposeInMainWorld("strideterm", {
  openExternal: (url) => ipcRenderer.invoke("shell:open-external", url),
  openTerminalPath: (request) => ipcRenderer.invoke("terminal:open-path", request),
  pasteClipboardImageForTerminal: () => ipcRenderer.invoke("clipboard:paste-image"),
  showSystemNotification: (payload) => ipcRenderer.invoke("notification:show-system", payload),
  checkForUpdates: () => ipcRenderer.invoke("app:check-for-updates"),
  checkCommand: (command) => ipcRenderer.invoke("app:check-command", command),
  getState: () => ipcRenderer.invoke("state:get"),
  activateWorkspace: (workspaceId) => ipcRenderer.invoke("workspace:activate", workspaceId),
  activateProject: (projectId) => ipcRenderer.invoke("project:activate", projectId),
  activateSession: (sessionId) => ipcRenderer.invoke("session:activate", sessionId),
  setWorkspaceUIState: (workspaceId, uiState) => ipcRenderer.invoke("workspace:set-ui-state", workspaceId, uiState),
  enableWorkspaceGrid: (layout, workspaceIds) => ipcRenderer.invoke("workspace-grid:enable", { layout, workspaceIds }),
  disableWorkspaceGrid: () => ipcRenderer.invoke("workspace-grid:disable"),
  setGridLayout: (layout) => ipcRenderer.invoke("workspace-grid:set-layout", { layout }),
  setGridCell: (cellIndex, workspaceId) => ipcRenderer.invoke("workspace-grid:set-cell", { cellIndex, workspaceId }),
  swapGridCells: (a, b) => ipcRenderer.invoke("workspace-grid:swap-cells", { a, b }),
  syncAttentionContext: (payload) => ipcRenderer.invoke("attention:sync", payload),
  clearAllAttention: () => ipcRenderer.invoke("attention:clear-all"),
  clearAlertForSession: (sessionId, options) => ipcRenderer.invoke("attention:clear-session", sessionId, options),
  saveWorkspace: (workspace) => ipcRenderer.invoke("workspace:save", workspace),
  saveProject: (project) => ipcRenderer.invoke("project:save", project),
  deleteWorkspace: (workspaceId, options) => ipcRenderer.invoke("workspace:delete", workspaceId, options),
  deleteProject: (projectId) => ipcRenderer.invoke("project:delete", projectId),
  reorderWorkspaces: (workspaceIds) => ipcRenderer.invoke("workspace:reorder", workspaceIds),
  reorderProjects: (projectIds) => ipcRenderer.invoke("project:reorder", projectIds),
  updateSettings: async (settings) => {
    const result = (await ipcRenderer.invoke("settings:update", settings)) as Record<string, unknown>;
    return result["payload"] ?? result;
  },
  verifyAzureConnection: (connection) => ipcRenderer.invoke("azure:verify-connection", connection),
  saveAzureConnection: (connection) => ipcRenderer.invoke("azure:save-connection", connection),
  deleteAzureConnection: (connectionId) => ipcRenderer.invoke("azure:delete-connection", connectionId),
  refreshAzure: () => ipcRenderer.invoke("azure:refresh"),
  queryAzureAuditLog: (filters) => ipcRenderer.invoke("azure:audit-log:query", filters),
  getAzureAuditStats: (filters) => ipcRenderer.invoke("azure:audit-log:stats", filters),
  markAzurePullRequestSeen: (prKey) => ipcRenderer.invoke("azure:pull-request:seen", prKey),
  openAzurePullRequest: (payload) => ipcRenderer.invoke("azure:pull-request:open", payload),
  commentAzurePullRequest: (payload) => ipcRenderer.invoke("azure:pull-request:comment", payload),
  updateAzureThreadStatus: (payload) => ipcRenderer.invoke("azure:pull-request:thread-status", payload),
  createReviewBridgeDraftComment: (payload) => ipcRenderer.invoke("review-bridge:draft-comment:create", payload),
  saveReviewBridgeDraft: (payload) => ipcRenderer.invoke("review-bridge:draft:save", payload),
  queueReviewBridgeDraft: (payload) => ipcRenderer.invoke("review-bridge:draft:queue", payload),
  deleteReviewBridgeDraft: (payload) => ipcRenderer.invoke("review-bridge:draft:delete", payload),
  deleteReviewBridgeComment: (payload) => ipcRenderer.invoke("review-bridge:comment:delete", payload),
  replyWithCodeChanges: (payload) => ipcRenderer.invoke("review-bridge:comment:reply-with-changes", payload),
  saveAgentPrompt: (payload) => ipcRenderer.invoke("review-bridge:agent-prompt:save", payload),
  deleteAgentPrompt: (payload) => ipcRenderer.invoke("review-bridge:agent-prompt:delete", payload),
  syncReviewBridgePullRequest: (payload) => ipcRenderer.invoke("review-bridge:pull-request:sync", payload),
  pushAndPublishReview: (payload) => ipcRenderer.invoke("review-bridge:pull-request:push-and-publish", payload),
  voteAzurePullRequest: (payload) => ipcRenderer.invoke("azure:pull-request:vote", payload),
  fetchAzureReviewWorkspace: (workspaceId) => ipcRenderer.invoke("azure:workspace:fetch", workspaceId),
  rebaseAzureReviewWorkspace: (workspaceId) => ipcRenderer.invoke("azure:workspace:rebase", workspaceId),
  pushAzureReviewWorkspace: (workspaceId, options) => ipcRenderer.invoke("azure:workspace:push", workspaceId, options),
  azureCreatePullRequest: (payload) => ipcRenderer.invoke("azure:create-pull-request", payload),
  azureListRemoteBranches: (payload) => ipcRenderer.invoke("azure:list-remote-branches", payload),
  azureQuickFixListProjects: (payload) => ipcRenderer.invoke("azure:quickfix:list-projects", payload),
  azureQuickFixListRepositories: (payload) => ipcRenderer.invoke("azure:quickfix:list-repositories", payload),
  azureQuickFixListBranches: (payload) => ipcRenderer.invoke("azure:quickfix:list-branches", payload),
  azureQuickFixCreate: (payload) => ipcRenderer.invoke("azure:quickfix:create", payload),
  rerunAzureCheck: (prKey, checkItem) => ipcRenderer.invoke("azure:rerun-check", prKey, checkItem),
  verifyGitHubConnection: (connection) => ipcRenderer.invoke("github:verify-connection", connection),
  saveGitHubConnection: (connection) => ipcRenderer.invoke("github:save-connection", connection),
  deleteGitHubConnection: (connectionId) => ipcRenderer.invoke("github:delete-connection", connectionId),
  refreshGitHub: () => ipcRenderer.invoke("github:refresh"),
  queryGitHubAuditLog: (filters) => ipcRenderer.invoke("github:audit-log:query", filters),
  getGitHubAuditStats: (filters) => ipcRenderer.invoke("github:audit-log:stats", filters),
  markGitHubPullRequestSeen: (prKey) => ipcRenderer.invoke("github:pull-request:seen", prKey),
  openGitHubPullRequest: (payload) => ipcRenderer.invoke("github:pull-request:open", payload),
  commentGitHubPullRequest: (payload) => ipcRenderer.invoke("github:pull-request:comment", payload),
  submitGitHubPullRequestReview: (payload) => ipcRenderer.invoke("github:pull-request:review", payload),
  rerunGitHubCheck: (prKey, checkItem) => ipcRenderer.invoke("github:rerun-check", prKey, checkItem),
  fetchGitHubReviewWorkspace: (workspaceId) => ipcRenderer.invoke("github:workspace:fetch", workspaceId),
  rebaseGitHubReviewWorkspace: (workspaceId) => ipcRenderer.invoke("github:workspace:rebase", workspaceId),
  pushGitHubReviewWorkspace: (workspaceId, options) =>
    ipcRenderer.invoke("github:workspace:push", workspaceId, options),
  githubListRemoteBranches: (payload) => ipcRenderer.invoke("github:list-remote-branches", payload),
  githubCreatePullRequest: (payload) => ipcRenderer.invoke("github:create-pull-request", payload),
  githubQuickFixListRepos: (payload) => ipcRenderer.invoke("github:quickfix:list-repos", payload),
  githubQuickFixListBranches: (payload) => ipcRenderer.invoke("github:quickfix:list-branches", payload),
  githubQuickFixCreate: (payload) => ipcRenderer.invoke("github:quickfix:create", payload),
  verifyTelegramConnection: (connection) => ipcRenderer.invoke("telegram:verify-connection", connection),
  detectTelegramChats: (connection) => ipcRenderer.invoke("telegram:detect-chats", connection),
  saveTelegramConnection: (connection) => ipcRenderer.invoke("telegram:save-connection", connection),
  deleteTelegramConnection: (connectionId) => ipcRenderer.invoke("telegram:delete-connection", connectionId),
  refreshTelegram: () => ipcRenderer.invoke("telegram:refresh"),
  regenerateRemoteToken: () => ipcRenderer.invoke("remote:token:regenerate"),
  configureClaudeHook: () => ipcRenderer.invoke("claude-hook:configure"),
  removeClaudeHook: () => ipcRenderer.invoke("claude-hook:remove"),
  getClaudeHookStatus: () => ipcRenderer.invoke("claude-hook:status"),
  testClaudeHook: () => ipcRenderer.invoke("claude-hook:test"),
  configureGeminiHook: () => ipcRenderer.invoke("gemini-hook:configure"),
  removeGeminiHook: () => ipcRenderer.invoke("gemini-hook:remove"),
  getGeminiHookStatus: () => ipcRenderer.invoke("gemini-hook:status"),
  testGeminiHook: () => ipcRenderer.invoke("gemini-hook:test"),
  configureCodexHook: () => ipcRenderer.invoke("codex-hook:configure"),
  removeCodexHook: () => ipcRenderer.invoke("codex-hook:remove"),
  getCodexHookStatus: () => ipcRenderer.invoke("codex-hook:status"),
  testCodexHook: () => ipcRenderer.invoke("codex-hook:test"),
  configureCopilotHook: () => ipcRenderer.invoke("copilot-hook:configure"),
  removeCopilotHook: () => ipcRenderer.invoke("copilot-hook:remove"),
  getCopilotHookStatus: () => ipcRenderer.invoke("copilot-hook:status"),
  testCopilotHook: () => ipcRenderer.invoke("copilot-hook:test"),
  configureOpencodeHook: () => ipcRenderer.invoke("opencode-hook:configure"),
  removeOpencodeHook: () => ipcRenderer.invoke("opencode-hook:remove"),
  getOpencodeHookStatus: () => ipcRenderer.invoke("opencode-hook:status"),
  testOpencodeHook: () => ipcRenderer.invoke("opencode-hook:test"),
  getNotificationMetrics: () => ipcRenderer.invoke("notifications:metrics"),
  // Task runner
  recheckClaude: () => ipcRenderer.invoke("task:recheck-claude"),
  checkProviders: () => ipcRenderer.invoke("task:check-providers"),
  checkIsGitRepo: (cwd) => ipcRenderer.invoke("task:check-git-repo", cwd),
  probeDirectory: (cwd) => ipcRenderer.invoke("fs:probe-directory", cwd),
  createTaskWorkspace: (payload) => ipcRenderer.invoke("task:create-workspace", payload),
  startTask: (payload) => ipcRenderer.invoke("task:start", payload),
  stopTask: (payload) => ipcRenderer.invoke("task:stop", payload),
  pauseTask: (payload) => ipcRenderer.invoke("task:pause", payload),
  resumeTask: (payload) => ipcRenderer.invoke("task:resume", payload),
  resetTask: (payload) => ipcRenderer.invoke("task:reset", payload),
  rejectTaskVerdict: (payload) => ipcRenderer.invoke("task:reject-verdict", payload),
  updateTaskDescription: (payload) => ipcRenderer.invoke("task:update-description", payload),
  resolveTaskRecovery: (decisions) => ipcRenderer.invoke("task-recovery:resolve", decisions),
  getTaskStatus: (workspaceId) => ipcRenderer.invoke("task:status", workspaceId),
  refreshTunnel: () => ipcRenderer.invoke("tunnel:refresh"),
  createCloudflareTunnel: () => ipcRenderer.invoke("tunnel:create"),
  stopCloudflareTunnel: () => ipcRenderer.invoke("tunnel:stop"),
  restartTerminal: (sessionId) => ipcRenderer.invoke("terminal:restart", sessionId),
  closeTerminal: (sessionId) => ipcRenderer.invoke("terminal:close", sessionId),
  getTerminalReplay: (sessionId) => ipcRenderer.invoke("terminal:replay", { sessionId }),
  refreshDocker: () => ipcRenderer.invoke("docker:refresh"),
  dockerLogsOpen: (payload) => ipcRenderer.invoke("docker:logs:open", payload),
  dockerLogsUpdate: (payload) => ipcRenderer.invoke("docker:logs:update", payload),
  dockerLogsClose: (payload) => ipcRenderer.invoke("docker:logs:close", payload),
  dockerComposeAction: (payload) => ipcRenderer.invoke("docker:compose-action", payload),
  dockerInspect: (payload) => ipcRenderer.invoke("docker:inspect", payload),
  dockerTop: (payload) => ipcRenderer.invoke("docker:top", payload),
  dockerStats: (payload) => ipcRenderer.invoke("docker:stats", payload),
  dockerShellOpen: (payload) => ipcRenderer.invoke("docker:shell:open", payload),
  dockerShellWrite: (payload) => ipcRenderer.invoke("docker:shell:write", payload),
  dockerShellResize: (payload) => ipcRenderer.invoke("docker:shell:resize", payload),
  dockerShellClose: (payload) => ipcRenderer.invoke("docker:shell:close", payload),
  dockerImageInspect: (payload) => ipcRenderer.invoke("docker:image:inspect", payload),
  dockerVolumeInspect: (payload) => ipcRenderer.invoke("docker:volume:inspect", payload),
  dockerNetworkInspect: (payload) => ipcRenderer.invoke("docker:network:inspect", payload),
  dockerImageRemove: (payload) => ipcRenderer.invoke("docker:image:remove", payload),
  dockerVolumeRemove: (payload) => ipcRenderer.invoke("docker:volume:remove", payload),
  dockerNetworkRemove: (payload) => ipcRenderer.invoke("docker:network:remove", payload),
  dockerImagePull: (payload) => ipcRenderer.invoke("docker:image:pull", payload),
  dockerImagePrune: (payload) => ipcRenderer.invoke("docker:image:prune", payload),
  dockerVolumePrune: (payload) => ipcRenderer.invoke("docker:volume:prune", payload),
  dockerNetworkPrune: (payload) => ipcRenderer.invoke("docker:network:prune", payload),
  dockerBuilderPrune: (payload) => ipcRenderer.invoke("docker:builder:prune", payload),
  dockerSystemDf: (payload) => ipcRenderer.invoke("docker:system:df", payload),
  dockerVolumeList: (payload) => ipcRenderer.invoke("docker:volume:list", payload),
  dockerVolumeRead: (payload) => ipcRenderer.invoke("docker:volume:read", payload),
  onDockerLogsWrite: (handler) => ipcRenderer.on("docker:logs:write", (_event, payload) => handler(payload)),
  onDockerLogsClose: (handler) => ipcRenderer.on("docker:logs:close", (_event, payload) => handler(payload)),
  onDockerShellData: (handler) => ipcRenderer.on("docker:shell:data", (_event, payload) => handler(payload)),
  onDockerShellClose: (handler) => ipcRenderer.on("docker:shell:close", (_event, payload) => handler(payload)),
  refreshGit: (projectId) => ipcRenderer.invoke("git:refresh", projectId),
  gitFetch: (payload) => ipcRenderer.invoke("git:fetch", payload),
  gitPull: (payload) => ipcRenderer.invoke("git:pull", payload),
  gitPush: (payload) => ipcRenderer.invoke("git:push", payload),
  gitCheckoutBranch: (payload) => ipcRenderer.invoke("git:checkout-branch", payload),
  gitCreateBranch: (payload) => ipcRenderer.invoke("git:create-branch", payload),
  gitMergeIntoCurrent: (payload) => ipcRenderer.invoke("git:merge-into-current", payload),
  gitRebaseOnto: (payload) => ipcRenderer.invoke("git:rebase-onto", payload),
  gitContinueOperation: (payload) => ipcRenderer.invoke("git:continue", payload),
  gitAbortOperation: (payload) => ipcRenderer.invoke("git:abort", payload),
  gitDiffPreview: (payload) => ipcRenderer.invoke("git:diff-preview", payload),
  gitCompareBranch: (payload) => ipcRenderer.invoke("git:compare-branch", payload),
  gitMergeCurrentIntoBase: (payload) => ipcRenderer.invoke("git:merge-into-base", payload),
  gitRemoveWorktree: (payload) => ipcRenderer.invoke("git:remove-worktree", payload),
  gitCommitAll: (payload) => ipcRenderer.invoke("git:commit-all", payload),
  gitStash: (payload) => ipcRenderer.invoke("git:stash", payload),
  gitStashPop: (payload) => ipcRenderer.invoke("git:stash-pop", payload),
  gitCommitDiff: (payload) => ipcRenderer.invoke("git:commit-diff", payload),
  gitCommitInfo: (payload) => ipcRenderer.invoke("git:commit-info", payload),
  gitLogPage: (payload) => ipcRenderer.invoke("git:log-page", payload),
  gitListTags: (payload) => ipcRenderer.invoke("git:list-tags", payload),
  gitCreateTag: (payload) => ipcRenderer.invoke("git:create-tag", payload),
  gitDeleteTag: (payload) => ipcRenderer.invoke("git:delete-tag", payload),
  gitPushTag: (payload) => ipcRenderer.invoke("git:push-tag", payload),
  gitPushAllTags: (payload) => ipcRenderer.invoke("git:push-all-tags", payload),
  gitDeleteRemoteTag: (payload) => ipcRenderer.invoke("git:delete-remote-tag", payload),
  gitForcePushWithLease: (payload) => ipcRenderer.invoke("git:force-push-with-lease", payload),
  dockerAction: (action, containerId) => ipcRenderer.invoke("docker:action", action, containerId),
  openDockerSession: (payload) => ipcRenderer.invoke("docker:open-session", payload),
  openLazydockerSession: (payload) => ipcRenderer.invoke("docker:open-lazydocker", payload),
  openLazygitSession: (payload) => ipcRenderer.invoke("git:open-lazygit", payload),
  createWorktree: (payload) => ipcRenderer.invoke("git:create-worktree", payload),
  listPlugins: () => ipcRenderer.invoke("plugins:list"),
  getPluginWorkspaceTemplate: (pluginId) => ipcRenderer.invoke("plugins:workspace-template", pluginId),
  saveProfile: (profile) => ipcRenderer.invoke("profile:save", profile),
  deleteProfile: (profileId) => ipcRenderer.invoke("profile:delete", profileId),
  activateProfile: (profileId) => ipcRenderer.invoke("profile:activate", profileId),
  getWindowId: () => startupWindowId || ipcRenderer.invoke("window:get-id"),
  focusWindow: () => ipcRenderer.invoke("window:focus-current"),
  createWindow: (profileId) => ipcRenderer.invoke("window:create", profileId),
  closeWindow: () => ipcRenderer.invoke("window:close"),
  onNewWindowShortcut: (handler) => ipcRenderer.on("shortcut:new-window", () => handler()),
  fileList: (p) => ipcRenderer.invoke("file:list", p),
  fileTree: (p) => ipcRenderer.invoke("file:tree", p),
  filePreview: (p) => ipcRenderer.invoke("file:preview", p),
  fileRead: (p) => ipcRenderer.invoke("file:read", p),
  fileWrite: (p) => ipcRenderer.invoke("file:write", p),
  fileCreateFile: (p) => ipcRenderer.invoke("file:create-file", p),
  fileCreateDir: (p) => ipcRenderer.invoke("file:create-dir", p),
  fileRename: (p) => ipcRenderer.invoke("file:rename", p),
  fileDelete: (p) => ipcRenderer.invoke("file:delete", p),
  fileMove: (p) => ipcRenderer.invoke("file:move", p),
  fileCopy: (p) => ipcRenderer.invoke("file:copy", p),
  fileOpenInExplorer: (p) => ipcRenderer.invoke("file:open-in-explorer", p),
  fileClipboardCopy: (p) => ipcRenderer.invoke("file:clipboard-copy", p),
  fileOpenInEditor: (p) => ipcRenderer.invoke("file:open-in-editor", p),
  fileInfo: (p) => ipcRenderer.invoke("file:info", p),
  fileGitStatus: (p) => ipcRenderer.invoke("file:git-status", p),
  fileGitRefs: (p) => ipcRenderer.invoke("file:git-refs", p),
  fileGitDiff: (p) => ipcRenderer.invoke("file:git-diff", p),
  fileCommitFiles: (p) => ipcRenderer.invoke("file:commit-files", p),
  fileCommitDiff: (p) => ipcRenderer.invoke("file:commit-diff", p),
  browseDirectory: (defaultPath) => ipcRenderer.invoke("dialog:browse-directory", defaultPath),
  browseFile: (options) => ipcRenderer.invoke("dialog:browse-file", options),
  resizeTerminal: (sessionId, size) => ipcRenderer.send("terminal:resize", sessionId, size),
  writeTerminal: (sessionId, data) => ipcRenderer.send("terminal:input", sessionId, data),
  onStateUpdated: (handler) => ipcRenderer.on("state:updated", (_event, payload) => handler(payload)),
  onTerminalData: (handler) => ipcRenderer.on("terminal:data", (_event, payload) => handler(payload)),
  onTerminalExit: (handler) => ipcRenderer.on("terminal:exit", (_event, payload) => handler(payload)),
  onSwitchWorkspace: (handler) => ipcRenderer.on("shortcut:switch-workspace", (_event, index) => handler(index)),
  onSwitchProject: (handler) => ipcRenderer.on("shortcut:switch-project", (_event, index) => handler(index)),
  onSwitchTab: (handler) => ipcRenderer.on("shortcut:switch-tab", (_event, direction) => handler(direction)),
  onSshAuthPrompt: (handler) => ipcRenderer.on("ssh:auth-prompt", (_event, payload) => handler(payload)),
  onSshHostKeyChange: (handler) => ipcRenderer.on("ssh:host-key-change", (_event, payload) => handler(payload)),
  onSshState: (handler) => ipcRenderer.on("ssh:state", (_event, payload) => handler(payload)),
  onSshConnectionState: (handler) => ipcRenderer.on("ssh:connection-state", (_event, payload) => handler(payload)),
  // --- SSH actions ---
  sshHostsList: () => ipcRenderer.invoke("ssh:hosts:list"),
  sshHostsCreate: (payload) => ipcRenderer.invoke("ssh:hosts:create", payload),
  sshHostsUpdate: (payload) => ipcRenderer.invoke("ssh:hosts:update", payload),
  sshHostsDelete: (payload) => ipcRenderer.invoke("ssh:hosts:delete", payload),
  sshHostsDuplicate: (payload) => ipcRenderer.invoke("ssh:hosts:duplicate", payload),
  sshHostsTest: (payload) => ipcRenderer.invoke("ssh:hosts:test", payload),
  sshKeysList: () => ipcRenderer.invoke("ssh:keys:list"),
  sshKeysImport: (payload) => ipcRenderer.invoke("ssh:keys:import", payload),
  sshKeysGenerate: (payload) => ipcRenderer.invoke("ssh:keys:generate", payload),
  sshKeysDelete: (payload) => ipcRenderer.invoke("ssh:keys:delete", payload),
  sshCertsList: () => ipcRenderer.invoke("ssh:certs:list"),
  sshCertsImport: (payload) => ipcRenderer.invoke("ssh:certs:import", payload),
  sshCertsDelete: (payload) => ipcRenderer.invoke("ssh:certs:delete", payload),
  sshAuthAnswer: (payload) => ipcRenderer.invoke("ssh:auth:answer", payload),
  sshAuthCancel: (payload) => ipcRenderer.invoke("ssh:auth:cancel", payload),
  sshHostKeyAccept: (payload) => ipcRenderer.invoke("ssh:host-key:accept", payload),
  sshHostKeyReject: (payload) => ipcRenderer.invoke("ssh:host-key:reject", payload),
  sshConfigPreview: (payload) => ipcRenderer.invoke("ssh:config:preview", payload),
  sshConfigImport: (payload) => ipcRenderer.invoke("ssh:config:import", payload),
  sshKnownHostsImport: (payload) => ipcRenderer.invoke("ssh:known-hosts:import", payload),
  startupFlags,
  logRenderer: (level, message, meta) => {
    // Fire-and-forget; the main handler validates and never throws back.
    try {
      ipcRenderer.send("log:renderer", level, message, meta);
    } catch {
      // If IPC is torn down (window closing) we silently drop the entry —
      // this is a logger, it must never break the caller.
    }
  },
} satisfies StridetermAPI);

// Tag <body> with the host platform so CSS can target macOS-only chrome
// (the hiddenInset traffic-light cutout that needs sidebar header padding).
// Win/Linux get matching classes for symmetry; the renderer reads them via
// `document.body.classList`. preload runs in an isolated context but shares
// the renderer DOM, so listening for DOMContentLoaded here is the standard
// way to mutate <body> before app code mounts.
window.addEventListener("DOMContentLoaded", () => {
  document.body.classList.add(`platform-${process.platform}`);
});
