import { contextBridge, ipcRenderer } from "electron";

contextBridge.exposeInMainWorld("strideterm", {
  openExternal: (url) => ipcRenderer.invoke("shell:open-external", url),
  getState: () => ipcRenderer.invoke("state:get"),
  activateWorkspace: (workspaceId) => ipcRenderer.invoke("workspace:activate", workspaceId),
  activateProject: (projectId) => ipcRenderer.invoke("project:activate", projectId),
  activateSession: (sessionId) => ipcRenderer.invoke("session:activate", sessionId),
  syncAttentionContext: (payload) => ipcRenderer.invoke("attention:sync", payload),
  saveWorkspace: (workspace) => ipcRenderer.invoke("workspace:save", workspace),
  saveProject: (project) => ipcRenderer.invoke("project:save", project),
  deleteWorkspace: (workspaceId) => ipcRenderer.invoke("workspace:delete", workspaceId),
  deleteProject: (projectId) => ipcRenderer.invoke("project:delete", projectId),
  reorderWorkspaces: (workspaceIds) => ipcRenderer.invoke("workspace:reorder", workspaceIds),
  reorderProjects: (projectIds) => ipcRenderer.invoke("project:reorder", projectIds),
  updateSettings: async (settings) => {
    const result = await ipcRenderer.invoke("settings:update", settings);
    return result.payload || result;
  },
  regenerateRemoteToken: () => ipcRenderer.invoke("remote:token:regenerate"),
  refreshTunnel: () => ipcRenderer.invoke("tunnel:refresh"),
  createCloudflareTunnel: () => ipcRenderer.invoke("tunnel:create"),
  stopCloudflareTunnel: () => ipcRenderer.invoke("tunnel:stop"),
  restartTerminal: (sessionId) => ipcRenderer.invoke("terminal:restart", sessionId),
  closeTerminal: (sessionId) => ipcRenderer.invoke("terminal:close", sessionId),
  refreshDocker: () => ipcRenderer.invoke("docker:refresh"),
  refreshGit: (projectId) => ipcRenderer.invoke("git:refresh", projectId),
  dockerAction: (action, containerId) => ipcRenderer.invoke("docker:action", action, containerId),
  openDockerSession: (payload) => ipcRenderer.invoke("docker:open-session", payload),
  openLazydockerSession: (payload) => ipcRenderer.invoke("docker:open-lazydocker", payload),
  openLazygitSession: (payload) => ipcRenderer.invoke("git:open-lazygit", payload),
  createWorktree: (payload) => ipcRenderer.invoke("git:create-worktree", payload),
  listPlugins: () => ipcRenderer.invoke("plugins:list"),
  getPluginWorkspaceTemplate: (pluginId) => ipcRenderer.invoke("plugins:workspace-template", pluginId),
  saveProfile: (profile) => ipcRenderer.invoke("profile:save", profile),
  deleteProfile: (profileId) => ipcRenderer.invoke("profile:delete", profileId),
  activateProfile: (profileId) => ipcRenderer.invoke("profile:activate", profileId),
  browseDirectory: (defaultPath) => ipcRenderer.invoke("dialog:browse-directory", defaultPath),
  browseFile: (options) => ipcRenderer.invoke("dialog:browse-file", options),
  resizeTerminal: (sessionId, size) => ipcRenderer.send("terminal:resize", sessionId, size),
  writeTerminal: (sessionId, data) => ipcRenderer.send("terminal:input", sessionId, data),
  onStateUpdated: (handler) => ipcRenderer.on("state:updated", (_event, payload) => handler(payload)),
  onTerminalData: (handler) => ipcRenderer.on("terminal:data", (_event, payload) => handler(payload)),
  onTerminalExit: (handler) => ipcRenderer.on("terminal:exit", (_event, payload) => handler(payload)),
  onSwitchWorkspace: (handler) => ipcRenderer.on("shortcut:switch-workspace", (_event, index) => handler(index)),
  onSwitchProject: (handler) => ipcRenderer.on("shortcut:switch-project", (_event, index) => handler(index)),
  onSwitchTab: (handler) => ipcRenderer.on("shortcut:switch-tab", (_event, direction) => handler(direction)),
});
