import { contextBridge, ipcRenderer } from "electron";

contextBridge.exposeInMainWorld("strideterm", {
  openExternal: (url) => ipcRenderer.invoke("shell:open-external", url),
  showSystemNotification: (payload) => ipcRenderer.invoke("notification:show-system", payload),
  getState: () => ipcRenderer.invoke("state:get"),
  activateWorkspace: (workspaceId) => ipcRenderer.invoke("workspace:activate", workspaceId),
  activateProject: (projectId) => ipcRenderer.invoke("project:activate", projectId),
  activateSession: (sessionId) => ipcRenderer.invoke("session:activate", sessionId),
  syncAttentionContext: (payload) => ipcRenderer.invoke("attention:sync", payload),
  clearAllAttention: () => ipcRenderer.invoke("attention:clear-all"),
  saveWorkspace: (workspace) => ipcRenderer.invoke("workspace:save", workspace),
  saveProject: (project) => ipcRenderer.invoke("project:save", project),
  deleteWorkspace: (workspaceId, options) => ipcRenderer.invoke("workspace:delete", workspaceId, options),
  deleteProject: (projectId) => ipcRenderer.invoke("project:delete", projectId),
  reorderWorkspaces: (workspaceIds) => ipcRenderer.invoke("workspace:reorder", workspaceIds),
  reorderProjects: (projectIds) => ipcRenderer.invoke("project:reorder", projectIds),
  updateSettings: async (settings) => {
    const result = await ipcRenderer.invoke("settings:update", settings);
    return result.payload || result;
  },
  verifyAzureConnection: (connection) => ipcRenderer.invoke("azure:verify-connection", connection),
  saveAzureConnection: (connection) => ipcRenderer.invoke("azure:save-connection", connection),
  deleteAzureConnection: (connectionId) => ipcRenderer.invoke("azure:delete-connection", connectionId),
  refreshAzure: () => ipcRenderer.invoke("azure:refresh"),
  queryAzureAuditLog: (filters) => ipcRenderer.invoke("azure:audit-log:query", filters),
  getAzureAuditStats: (filters) => ipcRenderer.invoke("azure:audit-log:stats", filters),
  markAzurePullRequestSeen: (prKey) => ipcRenderer.invoke("azure:pull-request:seen", prKey),
  openAzurePullRequest: (payload) => ipcRenderer.invoke("azure:pull-request:open", payload),
  commentAzurePullRequest: (payload) => ipcRenderer.invoke("azure:pull-request:comment", payload),
  updateAzureThreadStatus: (payload) => ipcRenderer.invoke("azure:pull-request:thread-status", payload),
  createReviewBridgeDraftComment: (payload) => ipcRenderer.invoke("review-bridge:draft-comment:create", payload),
  saveReviewBridgeDraft: (payload) => ipcRenderer.invoke("review-bridge:draft:save", payload),
  queueReviewBridgeDraft: (payload) => ipcRenderer.invoke("review-bridge:draft:queue", payload),
  deleteReviewBridgeDraft: (payload) => ipcRenderer.invoke("review-bridge:draft:delete", payload),
  deleteReviewBridgeComment: (payload) => ipcRenderer.invoke("review-bridge:comment:delete", payload),
  replyWithCodeChanges: (payload) => ipcRenderer.invoke("review-bridge:comment:reply-with-changes", payload),
  saveAgentPrompt: (payload) => ipcRenderer.invoke("review-bridge:agent-prompt:save", payload),
  deleteAgentPrompt: (payload) => ipcRenderer.invoke("review-bridge:agent-prompt:delete", payload),
  syncReviewBridgePullRequest: (payload) => ipcRenderer.invoke("review-bridge:pull-request:sync", payload),
  pushAndPublishReview: (payload) => ipcRenderer.invoke("review-bridge:pull-request:push-and-publish", payload),
  voteAzurePullRequest: (payload) => ipcRenderer.invoke("azure:pull-request:vote", payload),
  fetchAzureReviewWorkspace: (workspaceId) => ipcRenderer.invoke("azure:workspace:fetch", workspaceId),
  rebaseAzureReviewWorkspace: (workspaceId) => ipcRenderer.invoke("azure:workspace:rebase", workspaceId),
  pushAzureReviewWorkspace: (workspaceId, options) => ipcRenderer.invoke("azure:workspace:push", workspaceId, options),
  azureCreatePullRequest: (payload) => ipcRenderer.invoke("azure:create-pull-request", payload),
  azureListRemoteBranches: (payload) => ipcRenderer.invoke("azure:list-remote-branches", payload),
  azureQuickFixListProjects: (payload) => ipcRenderer.invoke("azure:quickfix:list-projects", payload),
  azureQuickFixListRepositories: (payload) => ipcRenderer.invoke("azure:quickfix:list-repositories", payload),
  azureQuickFixListBranches: (payload) => ipcRenderer.invoke("azure:quickfix:list-branches", payload),
  azureQuickFixCreate: (payload) => ipcRenderer.invoke("azure:quickfix:create", payload),
  verifyGitHubConnection: (connection) => ipcRenderer.invoke("github:verify-connection", connection),
  saveGitHubConnection: (connection) => ipcRenderer.invoke("github:save-connection", connection),
  deleteGitHubConnection: (connectionId) => ipcRenderer.invoke("github:delete-connection", connectionId),
  refreshGitHub: () => ipcRenderer.invoke("github:refresh"),
  queryGitHubAuditLog: (filters) => ipcRenderer.invoke("github:audit-log:query", filters),
  getGitHubAuditStats: (filters) => ipcRenderer.invoke("github:audit-log:stats", filters),
  markGitHubPullRequestSeen: (prKey) => ipcRenderer.invoke("github:pull-request:seen", prKey),
  openGitHubPullRequest: (payload) => ipcRenderer.invoke("github:pull-request:open", payload),
  commentGitHubPullRequest: (payload) => ipcRenderer.invoke("github:pull-request:comment", payload),
  submitGitHubPullRequestReview: (payload) => ipcRenderer.invoke("github:pull-request:review", payload),
  fetchGitHubReviewWorkspace: (workspaceId) => ipcRenderer.invoke("github:workspace:fetch", workspaceId),
  rebaseGitHubReviewWorkspace: (workspaceId) => ipcRenderer.invoke("github:workspace:rebase", workspaceId),
  pushGitHubReviewWorkspace: (workspaceId, options) => ipcRenderer.invoke("github:workspace:push", workspaceId, options),
  githubQuickFixListRepos: (payload) => ipcRenderer.invoke("github:quickfix:list-repos", payload),
  githubQuickFixListBranches: (payload) => ipcRenderer.invoke("github:quickfix:list-branches", payload),
  githubQuickFixCreate: (payload) => ipcRenderer.invoke("github:quickfix:create", payload),
  regenerateRemoteToken: () => ipcRenderer.invoke("remote:token:regenerate"),
  refreshTunnel: () => ipcRenderer.invoke("tunnel:refresh"),
  createCloudflareTunnel: () => ipcRenderer.invoke("tunnel:create"),
  stopCloudflareTunnel: () => ipcRenderer.invoke("tunnel:stop"),
  restartTerminal: (sessionId) => ipcRenderer.invoke("terminal:restart", sessionId),
  closeTerminal: (sessionId) => ipcRenderer.invoke("terminal:close", sessionId),
  refreshDocker: () => ipcRenderer.invoke("docker:refresh"),
  refreshGit: (projectId) => ipcRenderer.invoke("git:refresh", projectId),
  gitFetch: (payload) => ipcRenderer.invoke("git:fetch", payload),
  gitPush: (payload) => ipcRenderer.invoke("git:push", payload),
  gitCheckoutBranch: (payload) => ipcRenderer.invoke("git:checkout-branch", payload),
  gitCreateBranch: (payload) => ipcRenderer.invoke("git:create-branch", payload),
  gitMergeIntoCurrent: (payload) => ipcRenderer.invoke("git:merge-into-current", payload),
  gitRebaseOnto: (payload) => ipcRenderer.invoke("git:rebase-onto", payload),
  gitContinueOperation: (payload) => ipcRenderer.invoke("git:continue", payload),
  gitAbortOperation: (payload) => ipcRenderer.invoke("git:abort", payload),
  gitDiffPreview: (payload) => ipcRenderer.invoke("git:diff-preview", payload),
  gitMergeCurrentIntoBase: (payload) => ipcRenderer.invoke("git:merge-into-base", payload),
  gitRemoveWorktree: (payload) => ipcRenderer.invoke("git:remove-worktree", payload),
  gitCommitAll: (payload) => ipcRenderer.invoke("git:commit-all", payload),
  gitStash: (payload) => ipcRenderer.invoke("git:stash", payload),
  gitStashPop: (payload) => ipcRenderer.invoke("git:stash-pop", payload),
  gitCommitDiff: (payload) => ipcRenderer.invoke("git:commit-diff", payload),
  dockerAction: (action, containerId) => ipcRenderer.invoke("docker:action", action, containerId),
  openDockerSession: (payload) => ipcRenderer.invoke("docker:open-session", payload),
  openLazydockerSession: (payload) => ipcRenderer.invoke("docker:open-lazydocker", payload),
  openLazygitSession: (payload) => ipcRenderer.invoke("git:open-lazygit", payload),
  createWorktree: (payload) => ipcRenderer.invoke("git:create-worktree", payload),
  listPlugins: () => ipcRenderer.invoke("plugins:list"),
  getPluginWorkspaceTemplate: (pluginId) => ipcRenderer.invoke("plugins:workspace-template", pluginId),
  saveProfile: (profile) => ipcRenderer.invoke("profile:save", profile),
  deleteProfile: (profileId) => ipcRenderer.invoke("profile:delete", profileId),
  activateProfile: (profileId) => ipcRenderer.invoke("profile:activate", profileId),
  fileList: (p) => ipcRenderer.invoke("file:list", p),
  fileTree: (p) => ipcRenderer.invoke("file:tree", p),
  filePreview: (p) => ipcRenderer.invoke("file:preview", p),
  fileRead: (p) => ipcRenderer.invoke("file:read", p),
  fileWrite: (p) => ipcRenderer.invoke("file:write", p),
  fileCreateFile: (p) => ipcRenderer.invoke("file:create-file", p),
  fileCreateDir: (p) => ipcRenderer.invoke("file:create-dir", p),
  fileRename: (p) => ipcRenderer.invoke("file:rename", p),
  fileDelete: (p) => ipcRenderer.invoke("file:delete", p),
  fileMove: (p) => ipcRenderer.invoke("file:move", p),
  fileCopy: (p) => ipcRenderer.invoke("file:copy", p),
  fileOpenInExplorer: (p) => ipcRenderer.invoke("file:open-in-explorer", p),
  fileInfo: (p) => ipcRenderer.invoke("file:info", p),
  browseDirectory: (defaultPath) => ipcRenderer.invoke("dialog:browse-directory", defaultPath),
  browseFile: (options) => ipcRenderer.invoke("dialog:browse-file", options),
  resizeTerminal: (sessionId, size) => ipcRenderer.send("terminal:resize", sessionId, size),
  writeTerminal: (sessionId, data) => ipcRenderer.send("terminal:input", sessionId, data),
  onStateUpdated: (handler) => ipcRenderer.on("state:updated", (_event, payload) => handler(payload)),
  onTerminalData: (handler) => ipcRenderer.on("terminal:data", (_event, payload) => handler(payload)),
  onTerminalExit: (handler) => ipcRenderer.on("terminal:exit", (_event, payload) => handler(payload)),
  onSwitchWorkspace: (handler) => ipcRenderer.on("shortcut:switch-workspace", (_event, index) => handler(index)),
  onSwitchProject: (handler) => ipcRenderer.on("shortcut:switch-project", (_event, index) => handler(index)),
  onSwitchTab: (handler) => ipcRenderer.on("shortcut:switch-tab", (_event, direction) => handler(direction)),
});
