<template>
  <div class="dialog">
    <div class="dialog__header">
      <div>
        <p class="eyebrow">Agent Task Runner</p>
        <h2>Create task workspace</h2>
      </div>
      <button type="button" class="button button--ghost" @click="emit('cancel')">Close</button>
    </div>
    <form class="form" @submit.prevent="handleSubmit">
      <label>
        <span>{{ draft.useWorktree ? "Base repository" : "Project directory" }} <em class="required">*</em></span>
        <div class="input-with-action">
          <input
            v-model="draft.cwd"
            name="cwd"
            :placeholder="draft.useWorktree ? 'Path to git repository root' : 'Path to project root'"
            required
            maxlength="500"
          />
          <button
            v-if="api?.browseDirectory"
            type="button"
            class="button button--ghost input-with-action__btn"
            @click="browseCwd"
          >
            Browse
          </button>
        </div>
      </label>

      <label
        class="checkbox-label"
        title="Create a git worktree from the base repository so the task agent works on an isolated branch. This lets you run multiple tasks in parallel on the same repo."
      >
        <input v-model="draft.useWorktree" type="checkbox" />
        <span>Create in git worktree</span>
      </label>

      <label v-if="draft.useWorktree">
        <span>Branch name <em class="required">*</em></span>
        <input
          v-model="draft.worktreeBranch"
          name="worktreeBranch"
          placeholder="e.g. task/add-pagination"
          :required="draft.useWorktree"
          maxlength="200"
          pattern="[a-zA-Z0-9._/\-]+"
          title="Only letters, numbers, dots, hyphens, slashes, or underscores"
        />
        <span class="field-hint"
          >A new branch will be created from the current HEAD. The agent will work in an isolated worktree
          directory.</span
        >
      </label>

      <label
        title="This text will be written to TASK.md and sent as the initial prompt to the Worker agent. If left empty, the workspace opens without a task — you can write TASK.md manually or instruct the Worker directly in the terminal."
      >
        <span>Task assignment</span>
        <textarea
          v-model="draft.description"
          name="description"
          rows="5"
          placeholder='e.g. "Add pagination to the /api/users endpoint with 25 items per page. Include tests." — written to TASK.md and sent to the Worker. Leave empty to instruct the Worker manually.'
          maxlength="5000"
        />
      </label>

      <p v-if="!claudeAvailable" class="warning-box">
        Claude Code CLI (claude) was not found on your PATH. The Worker and Judge panels require it to run.
      </p>

      <p v-if="draft.useWorktree" class="info-box">
        The agent will work in <code>{{ worktreePreviewPath }}</code
        >. Control files, git commits, and all changes stay isolated in this worktree. You can run multiple worktree
        tasks on the same repo in parallel.
      </p>
      <p v-else class="info-box">
        Control files (TASK.md, TODO.md, FINISH_CRITERIA.md, WORK_LOCK) are created automatically. Verification commands
        are auto-detected from your project. You can edit everything in the Dashboard after creation.
      </p>

      <div class="grid">
        <label>
          <span>Max rounds</span>
          <input v-model.number="draft.maxRounds" name="maxRounds" type="number" min="1" max="100" />
        </label>
      </div>

      <footer class="dialog__footer">
        <button type="button" class="button button--ghost" :disabled="submitting" @click="emit('cancel')">
          Cancel
        </button>
        <button type="submit" class="button" :disabled="!canSubmit || submitting">
          {{ submitting ? "Creating\u2026" : "Create workspace" }}
        </button>
      </footer>
    </form>
  </div>
</template>

<script setup>
import { reactive, computed, inject, ref, watch } from "vue";
import { useAppStore } from "../../stores/app.js";

const props = defineProps({
  initialCwd: { type: String, default: "" },
  onSubmit: { type: Function, default: null },
});

const emit = defineEmits(["cancel"]);

const api = inject("api");
const store = useAppStore();

const draft = reactive({
  cwd: props.initialCwd || "",
  description: "",
  maxRounds: 10,
  useWorktree: false,
  worktreeBranch: "",
});

const submitting = ref(false);

// Claude availability is checked once at runtime startup and cached in payload
const claudeAvailable = computed(() => store.payload?.environment?.claudeAvailable !== false);

const canSubmit = computed(() => {
  if (!draft.cwd.trim()) return false;
  if (draft.useWorktree && !draft.worktreeBranch.trim()) return false;
  return true;
});

// Auto-generate branch name from description when user hasn't manually edited it
const branchAutoGenerated = ref(true);
watch(
  () => draft.description,
  (desc) => {
    if (!draft.useWorktree || !branchAutoGenerated.value) return;
    draft.worktreeBranch = slugifyBranch(desc);
  },
);
watch(
  () => draft.worktreeBranch,
  (val, oldVal) => {
    // If user clears the field, re-enable auto-generation
    if (!val && oldVal) {
      branchAutoGenerated.value = true;
      return;
    }
    // Detect manual edits: if the new value doesn't match what auto-gen would produce, lock it
    if (val && val !== slugifyBranch(draft.description)) {
      branchAutoGenerated.value = false;
    }
  },
);

function slugifyBranch(text) {
  if (!text) return "";
  return (
    "task/" +
    text
      .toLowerCase()
      .replace(/[^a-z0-9\s-]/g, "")
      .replace(/\s+/g, "-")
      .replace(/-+/g, "-")
      .replace(/^-|-$/g, "")
      .slice(0, 60)
  );
}

const worktreePreviewPath = computed(() => {
  const base = draft.cwd.trim().replace(/[\\/]+$/, "");
  const branch = (draft.worktreeBranch || "branch").replace(/\//g, "-");
  return base ? `${base}/.strideterm/tree/${branch}` : `.strideterm/tree/${branch}`;
});

async function browseCwd() {
  if (!api?.browseDirectory) return;
  const selected = await api.browseDirectory(draft.cwd || "");
  if (selected) draft.cwd = selected;
}

async function handleSubmit() {
  if (!props.onSubmit) return;
  submitting.value = true;
  try {
    const config = {
      cwd: draft.cwd.trim(),
      description: draft.description.trim() || "",
      maxRounds: draft.maxRounds,
    };
    if (draft.useWorktree) {
      config.useWorktree = true;
      config.worktreeBranch = draft.worktreeBranch.trim();
    }
    await props.onSubmit(config);
  } finally {
    submitting.value = false;
  }
}
</script>

<style scoped>
.required {
  color: #e57373;
  font-style: normal;
}
.warning-box {
  background: rgba(255, 152, 0, 0.12);
  border: 1px solid rgba(255, 152, 0, 0.3);
  color: #ffcc80;
  padding: 8px 12px;
  border-radius: 4px;
  font-size: 12px;
  line-height: 1.5;
}
.checkbox-label {
  display: flex;
  align-items: center;
  gap: 8px;
  cursor: pointer;
  user-select: none;
}
.checkbox-label input[type="checkbox"] {
  width: 16px;
  height: 16px;
  margin: 0;
  cursor: pointer;
}
.checkbox-label span {
  font-size: 13px;
}
.field-hint {
  display: block;
  font-size: 11px;
  color: var(--muted, #888);
  margin-top: 4px;
  line-height: 1.4;
}
</style>
